=== xapiens/RVPF/core/dtd/rvpf-scenarios.dtd
<!--
 Related Values Processing Framework.

 Copyright (C) 2003-2019 Serge Brisson.

 This software is distributable under the LGPL license.
 See details at the bottom of this file.

 $Id: rvpf-scenarios.dtd 3961 2019-05-06 20:14:59Z SFB $

 This is the XML DTD for the RVPF 'scenarios' and 'scenario' documents.

 The DOCTYPE declarations are

     <!DOCTYPE scenarios PUBLIC
         "-//Serge Brisson//DTD RVPF Scenarios//EN"
         "http://rvpf.org/dtd/rvpf-scenarios.dtd">

 and

     <!DOCTYPE scenario PUBLIC
         "-//Serge Brisson//DTD RVPF Scenarios//EN"
         "http://rvpf.org/dtd/rvpf-scenarios.dtd">
 -->

<!ENTITY % VERSION '"0.8.2"'>

<!--
                Root elements.
 -->

<!--
 -->

<!ELEMENT scenarios (scenario*)>
<!ATTLIST scenarios
        version CDATA %VERSION;>

<!--
 The 'scenario' element represents a single scenario.  Each scenario is
 run in a controlled environments: the Store and Processor services are
 restarted and the points values are purged.

 The 'title' of the scenario is written to the log.  The 'time' is used
 as an initial default time.  This time may be overriden on subsequent
 commands.

 A 'note' is only informative.

 A 'time' attribute in this and other elements may contain a date part
 (YYYY-MM-DD) and / or a time part (HH:MM:SS).  When both are present,
 they are separated by a whitespace.  The second may include a
 fractional part down to the millisecond. When only the date is
 supplied, the time is set to midnight.  When only the time is supplied,
 the date is set to the current default value from the scene, scenario,
 or the system.

 The 'from' attribute contains the location (absolute or relative) of
 the actual scenario definition.
  -->
<!ELEMENT scenario ((casting, scene*)?)>
<!ATTLIST scenario
        title CDATA #IMPLIED
        note CDATA #IMPLIED
        time CDATA #IMPLIED
        from CDATA #IMPLIED>

<!--
                Main elements.
 -->

<!--
 The 'casting' element contains the assignments of roles in the scenario
 to the actors selected by the 'director'.  This 'director' is a
 property which is set before reading the metadata, where it should
 usually condition which definitions are seen by using the 'if' and
 'unless' attributes.
 -->
<!ELEMENT casting (cast*)>
<!ATTLIST casting
        note CDATA #IMPLIED
        director CDATA #REQUIRED>

<!--
 A 'scene' groups a number of events within a scenario.  Its 'title' is
 logged and its 'time' may set a new default value.  At the end of a
 scene, any held message is committed.
 -->
<!ELEMENT scene (set | entry | action | exit | repeat | silence | break)*>
<!ATTLIST scene
        title CDATA #REQUIRED
        note CDATA #IMPLIED
        time CDATA #IMPLIED>

<!--
                Child elements.
 -->

<!--
 An 'action' describes a value produced by the Processor.  The 'role'
 refers to the Point associated to the value.  The 'time' is the
 timestamp of the value. The 'state' is the state of the value.  The
 'text' is the value.

 The 'line' attribute identifies the event in the log.

 A messaging transaction commit is done on the first 'action' or 'exit'
 after 'entry' elements.

 After being recognized, the value is forwarded to the Processor.
 -->
<!ELEMENT action EMPTY>
<!ATTLIST action
        note CDATA #IMPLIED
        line CDATA #IMPLIED
        role CDATA #REQUIRED
        time CDATA #REQUIRED
        state CDATA #IMPLIED
        text CDATA #IMPLIED>

<!--
 A 'break' element does nothing.

 This may be used to set a breakpoint for debugging.
 -->
<!ELEMENT break EMPTY>
<!ATTLIST break
        note CDATA #IMPLIED
        line CDATA #IMPLIED>

<!--
 The 'cast' element attributes a 'role' to an 'actor'.

 If the actor's name is not supplied, it is assumed to be the role's
 name.
 -->
<!ELEMENT cast EMPTY>
<!ATTLIST cast
        note CDATA #IMPLIED
        role CDATA #REQUIRED
        actor CDATA #IMPLIED>

<!--
 An 'entry' represents a new value sent to the Store.  See 'action' for
 the meaning of the attributes.

 After being recognized, the value is forwarded to the Processor.
 -->
<!ELEMENT entry EMPTY>
<!ATTLIST entry
        note CDATA #IMPLIED
        line CDATA #IMPLIED
        role CDATA #REQUIRED
        time CDATA #REQUIRED
        state CDATA #IMPLIED
        text CDATA #IMPLIED>

<!--
 An 'exit' represents the same kind of event as the 'action', except
 that the value is NOT forwarded to the Processor.
 -->
<!ELEMENT exit EMPTY>
<!ATTLIST exit
        note CDATA #IMPLIED
        line CDATA #IMPLIED
        role CDATA #REQUIRED
        time CDATA #REQUIRED
        state CDATA #IMPLIED
        text CDATA #IMPLIED>

<!--
 A 'repeat' asks to repeat an action.

 After being recognized, the value is forwarded to the Processor.
 -->
<!ELEMENT repeat EMPTY>
<!ATTLIST repeat
        note CDATA #IMPLIED
        line CDATA #IMPLIED
        role CDATA #REQUIRED
        time CDATA #REQUIRED>

<!--
 A 'set' represents the same kind of event as the 'entry', except that
 the value is NOT forwarded to the Processor.
 -->
<!ELEMENT set EMPTY>
<!ATTLIST set
        note CDATA #IMPLIED
        line CDATA #IMPLIED
        role CDATA #REQUIRED
        time CDATA #IMPLIED
        state CDATA #IMPLIED
        text CDATA #IMPLIED>

<!--
 A 'silence' element will commit the messaging transaction.

 This is useful when some 'action' or 'exit' steps are activated by a
 previous 'action' without an intervening 'entry'.
 -->
<!ELEMENT silence EMPTY>
<!ATTLIST silence
        note CDATA #IMPLIED
        time CDATA #IMPLIED
        line CDATA #IMPLIED>

<!--
 This is free software; you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License
 version 2.1 as published by the Free Software Foundation.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this software; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 -->

=== xapiens/RVPF/core/tests/config/scenarios/rvpf-scenario-3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE scenario PUBLIC
        "-//Serge Brisson//DTD RVPF Scenarios//EN"
        "http://rvpf.org/dtd/rvpf-scenarios.dtd">

<!--
 Related Values Processing Framework.

 $Id: rvpf-scenario-3.xml 3388 2017-03-14 16:36:04Z SFB $
 -->

<scenario title="Synchronization" time='2017-02-01'>

    <casting director='tests.scenario.3'>
        <cast role='BEGIN' actor='TESTS.BEGIN:TEXT'/>
        <cast role='END' actor='TESTS.END:TEXT'/>
        <cast role='QUARTER' actor='TESTS.QUARTER:CLOCK'/>
        <cast role='SYNC-COPY' actor='TESTS.SYNC-COPY:NUMERIC'/>
        <cast role='SYNC-ORIGINAL' actor='TESTS.SYNC-ORIGINAL:NUMERIC'/>
    </casting>

    <scene title="No data">
        <entry line='A1' role='QUARTER' time='01:00' text='0'/>
        <exit line='A2' role='SYNC-COPY' time='01:00'/>
    </scene>

    <scene title="Data retriggers">
        <entry line='B1' role='SYNC-ORIGINAL' time='00:15' text='1.0'/>
        <exit line='B2' role='SYNC-COPY' time='01:00' text='1.0'/>
    </scene>

    <scene title="Normal data">
        <entry line='C1' role='SYNC-ORIGINAL' time='01:15' text='2.0'/>
        <entry line='C2' role='QUARTER' time='01:15' text='0'/>
        <exit line='C3' role='SYNC-COPY' time='01:15' text='2.0'/>
        <entry line='C4' role='QUARTER' time='01:30' text='0'/>
        <exit line='C5' role='SYNC-COPY' time='01:30' text='2.0'/>
    </scene>

    <scene title="Late data">
        <entry line='D1' role='QUARTER' time='02:15' text='0'/>
        <entry line='D2' role='QUARTER' time='02:30' text='0'/>
        <entry line='D3' role='QUARTER' time='03:15' text='0'/>
        <exit line='D4' role='SYNC-COPY' time='02:15'/>
        <exit line='D5' role='SYNC-COPY' time='02:30'/>
        <exit line='D6' role='SYNC-COPY' time='03:15'/>
        <entry line='D7' role='SYNC-ORIGINAL' time='02:15' text='3.0'/>
        <exit line='D8' role='SYNC-COPY' time='02:15' text='3.0'/>
        <exit line='D9' role='SYNC-COPY' time='02:30' text='3.0'/>
    </scene>

    <scene title="End" time='+1'>
        <!-- Ensures that there are no more results. -->
        <entry line='Z1' role='BEGIN' time='01:00' state='Done' text='Z'/>
        <exit line='Z2' role='END' time='01:00' state='Done' text='Z'/>
    </scene>

</scenario>

<!-- End. -->

=== xapiens/RVPF/core/tests/config/scenarios/rvpf-scenario-4.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE scenario PUBLIC
        "-//Serge Brisson//DTD RVPF Scenarios//EN"
        "http://rvpf.org/dtd/rvpf-scenarios.dtd">

<!--
 Related Values Processing Framework.

 $Id: rvpf-scenario-4.xml 3388 2017-03-14 16:36:04Z SFB $
 -->

<scenario title="Running interval" time='2017-02-01'>

    <casting director='tests.scenario.4'>
        <cast role='BEGIN' actor='TESTS.BEGIN:TEXT'/>
        <cast role='END' actor='TESTS.END:TEXT'/>
        <cast role='ENTRY' actor='TESTS.ENTRY:NUMERIC'/>
        <cast role='HOUR' actor='TESTS.HOUR:CLOCK'/>
        <cast role='SUM' actor='TESTS.SUM:NUMERIC'/>
    </casting>

    <scene title="First hour">
        <entry line='A1' role='HOUR' time='01:00' text='0'/>
        <exit line='A2' role='SUM' time='01:00' text='0.0'/>
        <entry line='A3' role='ENTRY' time='01:15' text='1.0'/>
        <entry line='A4' role='ENTRY' time='01:45' text='3.0'/>
        <exit line='A5' role='SUM' time='01:00' text='4.0'/>
        <entry line='A6' role='ENTRY' time='01:30' text='2.0'/>
        <exit line='A7' role='SUM' time='01:00' text='6.0'/>
    </scene>

    <scene title="Second hour">
        <entry line='B1' role='HOUR' time='02:00' text='0'/>
        <exit line='B2' role='SUM' time='01:00' text='6.0'/>
        <exit line='B3' role='SUM' time='02:00' text='0.0'/>
        <entry line='B4' role='ENTRY' time='02:15' text='5.0'/>
        <entry line='B5' role='ENTRY' time='02:30' text='6.0'/>
        <exit line='B6' role='SUM' time='02:00' text='11.0'/>
    </scene>

    <scene title="Third hour">
        <entry line='C1' role='ENTRY' time='03:00' text='7.0'/>
        <entry line='C3' role='HOUR' time='03:00' text='0'/>
        <exit line='C4' role='SUM' time='03:00' text='7.0'/>
        <exit line='C5' role='SUM' time='02:00' text='11.0'/>
    </scene>

    <scene title="End" time='+1'>
        <!-- Ensures that there are no more results. -->
        <entry line='Z1' role='BEGIN' time='01:00' state='Done' text='Z'/>
        <exit line='Z2' role='END' time='01:00' state='Done' text='Z'/>
    </scene>

</scenario>

<!-- End. -->

=== xapiens/RVPF/core/tests/config/scenarios/rvpf-scenario-5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE scenario PUBLIC
        "-//Serge Brisson//DTD RVPF Scenarios//EN"
        "http://rvpf.org/dtd/rvpf-scenarios.dtd">

<!--
 Related Values Processing Framework.

 $Id: rvpf-scenario-5.xml 3388 2017-03-14 16:36:04Z SFB $
 -->

<scenario title="Inter/extra-polation" time='2017-02-01'>

    <casting director='tests.scenario.5'>
        <cast role='BEGIN' actor='TESTS.BEGIN:TEXT'/>
        <cast role='DATA' actor='TESTS.DATA:NUMERIC'/>
        <cast role='END' actor='TESTS.END:TEXT'/>
        <cast role='SNAPSHOT' actor='TESTS.SNAPSHOT:NUMERIC'/>
        <cast role='TRIGGER' actor='TESTS.TRIGGER:LOGICAL'/>
    </casting>

    <scene title='Introduction'>
        <set line='A1' role='DATA' time='00:01' text='1.0'/>
        <silence line='A2'/>
        <set line='A3' role='DATA' time='00:03' text='3.0'/>
        <set line='A4' role='DATA' time='00:04' text='4.0'/>
        <silence line='A5'/>
        <entry line='A6' role='TRIGGER' time='00:01'/>
        <entry line='A7' role='TRIGGER' time='00:02'/>
        <entry line='A8' role='TRIGGER' time='00:03'/>
        <entry line='A9' role='TRIGGER' time='00:04'/>
        <entry line='A10' role='TRIGGER' time='00:05'/>
        <action line='A11' role='SNAPSHOT' time='00:01' text='1.0'/>
        <action line='A12' role='SNAPSHOT' time='00:02' text='2.0'/>
        <action line='A13' role='SNAPSHOT' time='00:03' text='3.0'/>
        <action line='A14' role='SNAPSHOT' time='00:04' text='4.0'/>
        <action line='A15' role='SNAPSHOT' time='00:05' text='5.0'/>
    </scene>

    <scene title="End" time='+1'>
        <!-- Ensures that there are no more results. -->
        <entry line='Z1' role='BEGIN' time='01:00' state='Done' text='Z'/>
        <exit line='Z2' role='END' time='01:00' state='Done' text='Z'/>
    </scene>

</scenario>

<!-- End. -->

=== xapiens/RVPF/core/tests/config/scenarios/rvpf-scenario-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE scenario PUBLIC
        "-//Serge Brisson//DTD RVPF Scenarios//EN"
        "http://rvpf.org/dtd/rvpf-scenarios.dtd">

<!--
 Related Values Processing Framework.

 $Id: rvpf-scenario-1.xml 3388 2017-03-14 16:36:04Z SFB $
 -->

<scenario title="Miscellany" time='2017-02-01'>

    <casting director='tests.scenario.1'>
        <cast role='BEGIN' actor='TESTS.BEGIN:TEXT'/>
        <cast role='CONTROLLED' actor='TESTS.CONTROLLED:NUMERIC'/>
        <cast role='CUTOFF' actor='TESTS.CUTOFF:CLOCK'/>
        <cast role='END' actor='TESTS.END:TEXT'/>
        <cast role='FILTER-CONTROL' actor='TESTS.FILTER-CONTROL:LOGICAL'/>
        <cast role='HOUR' actor='TESTS.HOUR:CLOCK'/>
        <cast role='LOAD' actor='TESTS.LOAD:NUMERIC'/>
        <cast role='OVERLOAD' actor='TESTS.OVERLOAD:NUMERIC'/>
        <cast role='SLOPE' actor='TESTS.SLOPE:NUMERIC'/>
        <cast role='SWITCH' actor='TESTS.SWITCH:STATE'/>
        <cast role='TRAFFIC-1' actor='TESTS.TRAFFIC-1:STATE'/>
        <cast role='TRAFFIC-2' actor='TESTS.TRAFFIC-2:STATE'/>
        <cast role='X' actor='TESTS.X:NUMERIC'/>
        <cast role='X-CLONE' actor='TESTS.X.CLONE:NUMERIC'/>
        <cast role='Y' actor='TESTS.Y:NUMERIC'/>
    </casting>

    <scene title="Initial values">
        <set line='A1' role='SWITCH' time='00:00' state='Set' text='Off'/>
        <set line='A2' role='HOUR' time='00:00' state='Set' text='0'/>
        <set line='A3' role='LOAD' time='00:30' state='Set' text='80.0'/>
        <set line='A4' role='X' time='00:30' state='Set' text='1.0'/>
        <entry line='A5' role='FILTER-CONTROL' time='00:00' text='1'/>
        <silence line='A6'/>
    </scene>

    <scene title="First hour">
        <entry line='B1' role='HOUR' time='01:00' text='0'/>
        <entry line='B2' role='Y' time='01:00' text='10.0'/>
        <entry line='B3' role='LOAD' time='01:10' text='90.0'/>
        <entry line='B4' role='LOAD' time='01:25' text='100.0'/>
        <entry line='B5' role='LOAD' time='01:45' text='110.0'/>
        <action line='B6' role='SLOPE' time='01:00'/>
        <entry line='B7' role='X' time='01:30' text='2.0'/>
        <entry line='B8' role='SWITCH' time='01:00' text='1'/>
    </scene>

    <scene title="Second hour">
        <entry line='C1' role='HOUR' time='02:00' text='0'/>
        <entry line='C2' role='Y' time='02:00' text='20.0'/>
        <action line='C3' role='X-CLONE' time='01:30' text='2.0'/>
        <action line='C4' role='OVERLOAD' time='02:00' text='25.0'/>
        <action line='C5' role='TRAFFIC-1' time='02:00' text='Red'/>
        <action line='C6' role='SLOPE' time='02:00' text='10.0'/>
        <entry line='C7' role='LOAD' time='02:15' text='95.0'/>
        <entry line='C8' role='LOAD' time='02:30' text='105.0'/>
        <entry line='C9' role='LOAD' time='02:45' text='80.0'/>
        <entry line='C10' role='X' time='02:30' text='3.0'/>
        <silence line='C11'/>
        <action line='C12' role='TRAFFIC-2' time='02:00' text='Red'/>
        <action line='C13' role='X-CLONE' time='02:30' text='3.0'/>
    </scene>

    <scene title="Third hour">
        <entry line='D1' role='HOUR' time='03:00' text='0'/>
        <entry line='D2' role='Y' time='03:00' text='30.0'/>
        <action line='D3' role='OVERLOAD' time='03:00' text='50.0'/>
        <action line='D4' role='TRAFFIC-1' time='03:00' text='Green'/>
        <action line='D5' role='SLOPE' time='03:00' text='10.0'/>
        <silence line='D6'/>
        <action line='D7' role='TRAFFIC-2' time='03:00' text='Green'/>
    </scene>

    <scene title="Corrections">
        <entry line='E1' role='X' time='02:00' text='0.0'/>
        <entry line='E2' role='Y' time='02:00' text='25.0'/>
        <action line='E3' role='SLOPE' time='02:00' text='15.0'/>
        <action line='E4' role='SLOPE' time='03:00' text='5.0'/>
        <entry line='E5' role='BEGIN' time='2:00' text='A'/>
        <action line='E6' role='END' time='2:00' text='A'/>
        <repeat line='E7' role='OVERLOAD' time='02:00'/>
        <silence line='E8'/>
        <exit line='E9' role='CONTROLLED' time='2:00' text='15.0'/>
    </scene>

    <scene title="Cutoff control">
        <entry line='F1' role='BEGIN' time='11:00' text='B'/>
        <exit line='F2' role='END' time='11:00' text='B'/>
        <entry line='F3' role='CUTOFF' time='12:00' text='0'/>
        <silence line='F4'/>
        <entry line='F5' role='BEGIN' time='11:00' text='B'/>
        <entry line='F6' role='BEGIN' time='12:00' text='C'/>
        <action line='F7' role='END' time='12:00' text='C'/>
    </scene>

    <scene title="End" time='+1'>
        <!-- Ensures that there are no more results. -->
        <entry line='G1' role='BEGIN' time='01:00' state='Done' text='D'/>
        <exit line='G2' role='END' time='01:00' state='Done' text='D' note="No more results"/>
    </scene>

</scenario>

<!-- End. -->

=== xapiens/RVPF/pap/tests/config/scenarios/rvpf-scenario-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE scenario PUBLIC
        "-//Serge Brisson//DTD RVPF Scenarios//EN"
        "http://rvpf.org/dtd/rvpf-scenarios.dtd">

<!--
 Related Values Processing Framework.

 $Id: rvpf-scenario-1.xml 3028 2016-03-16 18:45:25Z SFB $
 -->

<scenario title="Capture" time='-2' note="Tests the captor engine">

    <casting director='tests.scenario.1'>
        <cast role='BEGIN'/>
        <cast role='CAPTURED-REFERENCE'/>
        <cast role='CAPTURED-STREAM'/>
        <cast role='END'/>
        <cast role='REFERENCE'/>
        <cast role='STREAM'/>
        <cast role='TRIGGER'/>
    </casting>

    <scene title="Before" note="Puts values before the trigger">
        <set line='A0' role='REFERENCE' time='00:00' text='0'/>
        <set line='A1' role='STREAM' time='00:01' text='1'/>
        <set line='A2' role='STREAM' time='00:02' text='2'/>
        <set line='A3' role='STREAM' time='00:03' text='3'/>
        <set line='A4' role='STREAM' time='00:04' text='4'/>
        <set line='A5' role='STREAM' time='00:05' text='5'/>
        <set line='A6' role='STREAM' time='00:06' text='6'/>
    </scene>

    <scene title="Action" note="Action on start">
        <entry line='B1' role='TRIGGER' time='00:06' text='1'/>
        <exit line='B2' role='CAPTURED-STREAM' time='00:03' text='3'/>
        <exit line='B3' role='CAPTURED-STREAM' time='00:04' text='4'/>
        <exit line='B4' role='CAPTURED-STREAM' time='00:05' text='5'/>
        <exit line='B5' role='CAPTURED-STREAM' time='00:06' text='6'/>
        <exit line='B6' role='CAPTURED-REFERENCE' time='00:00' text='0'/>
        <set line='B7' role='STREAM' time='00:07' text='7'/>
        <set line='B8' role='STREAM' time='00:08' text='8'/>
        <set line='B9' role='STREAM' time='00:09' text='9'/>
        <set line='B10' role='STREAM' time='00:10' text='10'/>
        <silence line='B11' time='00:10'/>
        <action line='B12' role='TRIGGER' time='00:10' text='0'/>
        <set line='B13' role='STREAM' time='00:11' text='11'/>
    </scene>

    <scene title="Conclusion" note="Action on stop">
        <entry line='C1' role='TRIGGER' time='00:11' text='0'/>
        <exit line='C2' role='CAPTURED-STREAM' time='00:07' text='7'/>
        <exit line='C3' role='CAPTURED-STREAM' time='00:08' text='8'/>
        <exit line='C4' role='CAPTURED-STREAM' time='00:09' text='9'/>
    </scene>

    <scene title="End" time='+1' note="Ensures no more results">
        <entry line='Z1' role='BEGIN' time='01:00' text='Z'/>
        <exit line='Z2' role='END' time='01:00' text='Z'/>
    </scene>

</scenario>

<!-- End. -->
